
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='panel-components',
    version='0.1.2',
    description='HTML components for Panel templates.',
    python_requires='==3.*,>=3.6.0',
    author='Paulo Lopes',
    author_email='paulopes00@gmail.com',
    license='Apache-2.0',
    packages=['panel_components'],
    package_dir={"": "."},
    package_data={"panel_components": ["www/ace/*.js", "www/bokeh/*.css", "www/bokeh/*.js", "www/katex/*.css", "www/katex/*.js", "www/katex/fonts/*.woff", "www/mathjax/*.js", "www/plotly/*.js", "www/vega/*.js", "www/vtk/*.js", "www/vue/*.js"]},
    install_requires=['panel==0.*,>=0.9.7'],
)
